# Generated by Django 3.0.2 on 2020-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=10)),
                ('card_description', models.CharField(blank=True, max_length=200, null=True)),
                ('card_point', models.CharField(blank=True, max_length=100, null=True)),
                ('card_discount_event', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'creditcards',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_period', models.CharField(max_length=10)),
                ('credit_card', models.ManyToManyField(to='order.CreditCard')),
            ],
            options={
                'db_table': 'installmentPeriod',
            },
        ),
    ]
