# Generated by Django 3.0.2 on 2020-03-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_black_url', models.CharField(max_length=2000)),
                ('icon_active_url', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.MainCategory')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
    ]
