# Generated by Django 3.0.3 on 2020-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfomation',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailinfomation',
            name='product_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailinfomation',
            name='product_infomation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon_active_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon_black_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contactant',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_type_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sticker_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_text',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
